### ISSUE TITLE
Mobile version?

### ISSUE THREAD

**Issue by DrKat123** [iliketocode/bored#14]
So, mostly our visitors would likely be using phones (including me), so should there be a mobile CSS?

**Comment by Mrcomputer1** [comment]
If you work on the mobile CSS I could make something that automatically switches to the mobile CSS

**Comment by DrKat123** [comment]
Hmm, okay then :smiley_cat:

**Comment by iliketocode** [comment]
Definitely!

**Comment by Mrcomputer1** [comment]
@iliketocode shouldn't this be left open until it is complete?

**Comment by iliketocode** [comment]
Oh sorry, I was tired.

**Comment by DrKat123** [comment]
Should i add ` <meta name=viewport content='width=700'>` on every page temporarily? that should help make the pages fit for small screens :wink:

**Comment by Mrcomputer1** [comment]
@DrKat123 - I not sure if that would work. It would break the navigation bar.
![What mobile would look like](http://i63.tinypic.com/2rvzlw9.png)

Maybe don't add it - it not that bad to just zoom in until the mobile mode is complete.

**Comment by iliketocode** [comment]
It seems to work fine on iPads and tablets.
![ipad view](https://cloud.githubusercontent.com/assets/15147087/11958749/9c09456e-a8c1-11e5-919c-4c01405391bf.PNG)

**Comment by iliketocode** [comment]
It works fine on iPad

**Comment by DrKat123** [comment]
Hmm. ok then

**Comment by Mrcomputer1** [comment]
I think I have made a mobile version! I just have to test it on a mobile device then I will make a pull request (and push the code to the branch Mrcomputer1-mobile)!

**Comment by DrKat123** [comment]
I have another idea...
Use Bootstrap and add this:
```Html
<meta name="viewport" content="width=device-width, initial-scale=1">
```
to the
```html
<head>
</head>
```
Tag
@Mrcomputer1 ok

**Comment by Mrcomputer1** [comment]
Do you mean replace the CSS I made with Bootstrap's CSS because I would prefer not to do that. (Idea: Bootstrap version which is a modification of the mobile version to add bootstrap)

**Comment by DrKat123** [comment]
@Mrcomputer1 well, we could try

**Comment by Mrcomputer1** [comment]
Do you mean the Bootstrap version of the site?

Also, My iPod does not want to connect to my server I have on my laptop so I can test it :angry: and it just ran out of battery.

**Comment by DrKat123** [comment]
@Mrcomputer1 :laughing: seriously?
Bootstrap version of the site would be nice (hey that rhymes :stuck_out_tongue:)

**Comment by Mrcomputer1** [comment]
NOTE: This issue should close automatically when the pull request #16 is closed! So don't close this!

**Comment by DrKat123** [comment]
Oh, btw nice. tested dis on Apache

**Comment by Mrcomputer1** [comment]
@DrKat123 did it work well and look good?

**Comment by DrKat123** [comment]
Yes, resized my screen and so far so good

**Comment by Mrcomputer1** [comment]
:smile: now we only need @iliketocode to like it then we can merge it!

**Comment by DrKat123** [comment]
:ok_hand: :stuck_out_tongue_closed_eyes:

**Comment by Mrcomputer1** [comment]
Oh no I just found a bug. I will quickly fix it...
