### ISSUE TITLE
GA? (Google Analytics?)

### ISSUE THREAD

**Issue by DrKat123** [iliketocode/bored#15]
Should i add something like a web analytics like GA?

**Comment by DrKat123** [comment]
btw here's the code for GA:
```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71064270-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by Mrcomputer1** [comment]
UA-71064270-1 is the GA code for your site. You would need a different one for this site. Also can you add people to be able to see the GA for this site?

**Comment by DrKat123** [comment]
Ok.

**Comment by iliketocode** [comment]
Oh cool!

**Comment by DrKat123** [comment]
Generated the code. here it is
```html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-71903334-1', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by DrKat123** [comment]
O yeah, i need your email address if you and @Mrcomputer1 wants to see the GA report
(better sign up for a Google account :stuck_out_tongue:)

**Comment by DrKat123** [comment]
Ok, i have added the GA tracking code. it should work within 2 days :sob:

**Comment by Mrcomputer1** [comment]
@DrKat123 Can you add my google account? I posted the email on the Bored Activities forum in the mod forum

**Comment by DrKat123** [comment]
@Mrcomputer1 ok

**Comment by DrKat123** [comment]
@Mrcomputer1 now you can see the reports by logging in to your G+ account and then log in to google.com/analytics

**Comment by Mrcomputer1** [comment]
Should the GA code be on all the pages?

**Comment by DrKat123** [comment]
Oops :stuck_out_tongue:

**Comment by DrKat123** [comment]
Ok, every page has a GA tracking code now. Closing issue...

**Comment by Mrcomputer1** [comment]
I connected the Google Custom Search with the GA

**Comment by DrKat123** [comment]
Ok

**Comment by iliketocode** [comment]
Could yous guys just post screenshots of Analytics in the mod forum as I don't like to give out emails?

**Comment by DrKat123** [comment]
Oh, ok then
