### ISSUE TITLE
Active on other account

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#19]
If you see a contributor called @funsites don't worry cos its just me! :smile_cat:

**Comment by Mrcomputer1** [comment]
@iliketocode / @funsites Ok.

**Comment by DrKat123** [comment]
Wait you can do that? :gasp:

**Comment by funsites** [comment]
@Mrcomputer1 Because FunSites is the name of a site I am also working on (funsites.github.io/home if you are interested :+1: ) and I didn't want to change the bored domain :smile:

**Comment by iliketocode** [comment]
Oh yeah, don't worry if I kinda jump between accounts. I seem to do that. xD

**Comment by DrKat123** [comment]
:stuck_out_tongue: hey i do that on Scratch all the time XD

**Comment by iliketocode** [comment]
:laughing:
