### ISSUE TITLE
What color shall we make the site?

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#2]
@Mrcomputer1 
You said you could do CSS styling? Could we make a background colour?
What color do you think is good?

**Comment by iliketocode** [comment]
Also, I think it would be good to have a different bright color for every page to make the site look playful!
What about you?

**Comment by iliketocode** [comment]
Or if you like this sort of colour #00FF99

**Comment by Mrcomputer1** [comment]
I made the site #00FF99
I also added a search box which does not yet work (same reason Scratch projects, users and studios don't appear for a while)

You can see my pull request at https://github.com/iliketocode/bored/pull/3

**Comment by iliketocode** [comment]
@Mrcomputer1 That looks awesome!

**Comment by iliketocode** [comment]
@Mrcomputer1 I will make gh-pages default now
