### ISSUE TITLE
Link fixing

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#22]
@Mrcomputer1 You will need to do this because we cannot edit your forum. The Bored Activities button on the forums is  a link to the forums mainpage. Would it be better if it took you back to the actual Bored Activities site homepage? Only if you want to though! :smile:

**Comment by DrKat123** [comment]
Yeah XD

**Comment by Mrcomputer1** [comment]
It used to have a link at the bottom of the page but when I updated it I replaced the footer.html file. I will bring that link back. Do you want it to be in the header instead?

**Comment by iliketocode** [comment]
@mrcomputer1 That would be good!

**Comment by DrKat123** [comment]
@Mrcomputer1 thanks

**Comment by Mrcomputer1** [comment]
@iliketocode @funsites @DrKat123 
I added a link to the website called "The Website" (it replaced the Change your password link which was moved to the user page)

**Comment by DrKat123** [comment]
Ok then :)

**Comment by Mrcomputer1** [comment]
I forgot something
I disabled debug mode so 404 pages are not Django 404 pages, 403 pages are not Django 403 pages and 500 pages are not Django 500 pages (well they are but not debug mode Django 500 pages)

**Comment by DrKat123** [comment]
Lol
