### ISSUE TITLE
Author pages

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#5]
When we write "by ______", your username should link to a page. The page could be your own author page where you can write what you like to do on the site! What do you think?

**Comment by Mrcomputer1** [comment]
I like the idea.
 I also have a few ideas to add to it:
* Put all author pages in an authors folder
* Have a page with a list of authors (index.html in authors folder)
* Add authors page to header

Also would you like me to do it or do you want to do it?

**Comment by iliketocode** [comment]
I have made the folder and added two blank pages based on the template.

**Comment by iliketocode** [comment]
Filled in most of the to do list but adding a link on every page would be hard since I don't know how to code headers. Could you help with that?

**Comment by iliketocode** [comment]
@Mrcomputer1 - Could you add the links to the author pages in the header and where it goes on the site? I can't code headings very well!

**Comment by Mrcomputer1** [comment]
Ok I am working on it now... (Will edit this when done)

**Comment by iliketocode** [comment]
@Mrcomputer1 You can close things if they are complete. :smile:
