### ISSUE TITLE
Latest news?

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#6]
I could create a blog folder where we could post the latest news. This would need to be added in the header though and that would take a long time, so should we use the wiki instead, or could you do it if we started to make a blog?

**Comment by Mrcomputer1** [comment]
I like the idea! But I think we should have a forum (like suggested in issue #7) that has a News forum which acts like a blog

**Comment by iliketocode** [comment]
Oops! We forgot to close this! I'll do it now,

**Comment by iliketocode** [comment]
I added duplicate by accident and then removed again. I will reopen this when needed
