### ISSUE TITLE
Forum

### ISSUE THREAD

**Issue by Mrcomputer1** [iliketocode/bored#7]
I think this should have a forum thing.
I made an example forum at https://boredactivitiesforum.herokuapp.com/

If you like it then I could add a link to it on the website!

Also to get an admin account on it then register on it then tell me your username on it so I can make you admin.

You suggested a blog like thing in issue #6 - the "News" forum on this could be used as a blog!

**Comment by iliketocode** [comment]
That looks cool! Could you implement it into the site?

**Comment by Mrcomputer1** [comment]
I have added a link to the forum in the header.
@iliketocode could you create an account so I give you admin access to the site?

**Comment by iliketocode** [comment]
OK! Coming up!

**Comment by iliketocode** [comment]
@Mrcomputer1 : I get a Internal Server Error - HTTP 500 error when I register. Could you make a fix for this? :smiley_cat:

**Comment by Mrcomputer1** [comment]
@iliketocode: Fixed! (I think!)

**Comment by iliketocode** [comment]
@Mrcomputer1: It doesn't seem to be working. There is still an error.

**Comment by Mrcomputer1** [comment]
@iliketocode: 
The admin panel shows that you have created an account
![](http://i64.tinypic.com/260brrt.jpg)

When you register it does not say success it just sends you to the login page which looks exactly like the register page except for the signup/login button

I have made the "iliketocode" account admin [Click here](http://boredactivitiesforum.herokuapp.com/account/login/) to login

Also [see this](https://github.com/iliketocode/bored/wiki/Guide-to-doing-things-on-the-forum-\(includes-admin-mod-things\)) guide I made that shows how to use the forum system admin/mod things (shows simple and hard things)

**Comment by iliketocode** [comment]
OK, thanks! :laughing:
