### ISSUE TITLE
Read this please

### ISSUE THREAD

**Issue by iliketocode** [iliketocode/bored#8]
I have added blogs to user pages. just edit your user page as you normally do, with the HTML editor. Don't make your posts too long. just little updates!
Sign them with a Last edited date written in small bold. 

Thank you!

**Comment by Mrcomputer1** [comment]
Ok

**Comment by iliketocode** [comment]
@Mrcomputer1 The reason I am making less edits is because  my computer is being repaired. I think I might be getting it back today. It's hard to make edits on an iPad because of autocorrect.

**Comment by Mrcomputer1** [comment]
Why not just disable Autocorrect while editing?

**Comment by iliketocode** [comment]
@Mrcomputer1 - It's fine now. The computer is repaired! 
![my startup picture](https://cloud.githubusercontent.com/assets/15147087/11045115/7ca04346-871d-11e5-8673-2cdef8dacc3e.PNG)
I am going to make my desktop a little more interesting though...
